Filtering fields from metadata templates
phac-nml/irida pull request #1068
Opened 2021-08-04 18:55 UTC by tom114

## Description of changes
This PR is adding features to filter the metadata fields that are associated with a MetadataTemplate.  It required changes to a number of places where we interact with MetadataTemplates.

* Changing the way you read `MetadataTemplateField` for a `MetadataTemplate`.  Instead of them being read from the MetadataTemplate entity you now read them from a service method.  This allows us to filter to return only permitted fields.
* Removing `ProjectMetadataTemplateJoin` so that its enforced that a `MetadataTemplate` only belongs to one `Project`.  This was to help ensure that we were only reading fields we were allowed to read when reading a template.
* Moving the where we set the default template for a project into `MetadataTemplate`.  This avoids a cyclical reference in the database.

## Related issue
Related to #931

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

~* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
* [x] Tests added (or description of how to test) for any new features.
~* [ ] User documentation updated for UI or technical changes.~

2021-08-04 19:36 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
> -
We don't need to go through template fields anymore because they're requested above in the `getPermittedFieldsForCurrentUser` function.

2021-08-04 19:38 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/MetadataTemplateServiceImpl.java
> +	}
This is the main addition.  Basically it's just reusing the `getPermittedFieldsForCurrentUser` function to filter out which fields from the template can be displayed.

2021-08-04 19:39 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/MetadataTemplateServiceImpl.java
> +		if (includeTemplateFields) {
Added a flag here for whether to include template fields when reading permitted fields for a user.

2021-08-05 19:14 UTC, deepsidhu85 requested changes
Overall this looks great. Just one thing below for now

2021-08-06 13:49 UTC, tom114 commented on src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.09/one-project-per-template.xml
> +            <column name="project_default" type="bit(1)" value="0">
Thanks @deepsidhu85 , I wasn't seeing it but might be different with versions or something.  Change to `valueBoolean` in 51b0ae8283.

2021-08-06 18:32 UTC, deepsidhu85 commented on src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/21.09/one-project-per-template.xml
> +            <column name="project_default" type="bit(1)" value="0">
Thanks @tom114!

2021-08-06 18:33 UTC, deepsidhu85 approved these changes

2021-08-06 18:41 UTC, joshsadam approved these changes
This all seems to work the way we are hoping.  Just checked through it as well on my mac.  Tom, you rock.  Thanks for taking care of this stuff.

2021-08-06 18:54 UTC, merged