Fixes filter by file exports all samples
phac-nml/irida pull request #1091
Opened 2021-09-16 19:23 UTC by joshsadam

## Description of changes
**Previously**: When filter by file was applied and the user tried to export the samples to excel or csv, the download would contain all the samples in the project.

**Fix**:  By default when filter by file is applied the filtered samples are selected. I am using this system to send the selected sample ids to the server and filtering the samples based on this list.

## Related issue
Fixes #985 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [X] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] ~~Tests added (or description of how to test) for any new features.~~
* [ ] ~~User documentation updated for UI or technical changes.~~

2021-09-21 15:48 UTC, tom114 requested changes
In testing this seems to work as expected. Thanks for the update.  Please add a bit of JS comments to the sections below and it's good to go!

2021-09-21 17:29 UTC, joshsadam commented on src/main/webapp/resources/js/utilities/file-utilities.js
> +export function downloadPost(url, contents) {
Updated in 668eb52c1dd1c2183d29c6dec4c25dec378e2fb6

2021-09-21 17:29 UTC, joshsadam commented on src/main/webapp/resources/js/pages/projects/samples/project-samples.js
> +    downloadPost(`${url}`, data);
Updated in 668eb52c1dd1c2183d29c6dec4c25dec378e2fb6

2021-09-22 19:51 UTC, tom114 approved these changes

2021-09-22 19:51 UTC, merged