Share samples from linelist page
phac-nml/irida pull request #1133
Opened 2021-11-19 17:58 UTC by joshsadam

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2021-11-23 21:35 UTC, deepsidhu85 requested changes
Looks good just a couple of changes below

2021-11-24 20:22 UTC, joshsadam commented on src/main/webapp/resources/js/pages/projects/linelist/components/ShareSampleButton/index.jsx
> +
Done in 8b499b8fdf4d4d88f8e21fcb5ee176e180a9c628

2021-11-24 20:22 UTC, joshsadam commented on src/main/webapp/resources/js/pages/projects/linelist/components/ShareSampleButton/index.jsx
> +      owner: sample.ownder,
Done

2021-11-24 22:14 UTC, deepsidhu85 approved these changes

2021-11-24 22:14 UTC, merged