Spring hateoas 1.0
phac-nml/irida pull request #1137
Opened 2021-12-02 16:22 UTC by ericenns

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

Upgraded spring-hateoas from 0.19.0 to 1.0.3. This is required for migration of the application over to Sprint-Boot 2.2.X.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2021-12-07 17:33 UTC, ksierks approved these changes
Awesome! Curious if you used the migrate-to-1.0.sh script? I tested random API endpoints, including the content negotiator. Looks good to me.

2021-12-07 17:35 UTC, ericenns commented
@ksierks I did end up using the `migrate-to-1.0.sh` script, just not on the entire repo only on the files that actually use `spring-hateoas`.

2021-12-16 19:11 UTC, deepsidhu85 requested changes
Just a few questions and changes. Otherwise looking good

**SampleSequenceFilesControllerTest.java**

Line 218: assertNotNull(qc.getLink(RESTSampleSequenceFilesController.REL_QC_SEQFILE));

**RESTSampleAssemblyControllerTest**

Line 76: assertNotNull("has self rel", genomeAssembly.getLink("self"));
Line 87: assertNotNull("has self rel", genomeAssembly.getLink("self"));

**RootControllerTest**

Line 50: assertNotNull(r.getLink("self"));
Line 51: assertNotNull(r.getLink("version"));

Is the  `.map(i -> i)`.orElse(null) not required for some of these and IanaLinkRelations.SELF for some of them?

2021-12-16 20:12 UTC, ericenns commented on CHANGELOG.md
> +* [DEVELOPER]: Upgraded Spring Hateoas to 1.0.3.RELEASE
Resolved in 4dc1f5effd6bbc9925f8440d57bcac7c4b4a6c5b

2021-12-16 20:17 UTC, deepsidhu85 commented on CHANGELOG.md
> +* [DEVELOPER]: Upgraded Spring Hateoas to 1.0.3.RELEASE
Thanks for taking care of that!

2021-12-16 20:17 UTC, deepsidhu85 approved these changes

2021-12-16 22:14 UTC, merged