Update create remote client
phac-nml/irida pull request #1152
Opened 2021-12-23 17:07 UTC by joshsadam

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Fixes #1117

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2022-01-11 19:03 UTC, ksierks requested changes
I took a peek all the files that aren't tests so far. Sorry for all the questions.

2022-02-17 20:14 UTC, joshsadam commented on src/main/webapp/resources/js/pages/remote-apis/RemoteApiPage.jsx
> +              <AddNewButton text={i18n("remoteapi.add")} />
As a child?  It allows the modal to use anything as the toggle for opening.  Just makes more reusable code.  I have been trying to use this pattern more and more.

2022-02-18 18:14 UTC, joshsadam commented on CHANGELOG.md
> +
Cleaned up when I merged development

2022-02-18 18:55 UTC, joshsadam commented on src/main/resources/i18n/messages.properties
>  remoteapi.details.title=Remote Connection Details
I think I got them all, thanks

2022-02-24 19:47 UTC, joshsadam commented on src/main/webapp/resources/js/pages/remote-apis/RemoteApiPage.jsx
> +              <AddNewButton text={i18n("remoteapi.add")} />
Updated in d141d33

2022-02-24 19:47 UTC, joshsadam commented on src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiStatus.jsx
>        setLoading(false);
Updated in d141d33

2022-02-24 19:50 UTC, ksierks approved these changes
Looks good to me.

2022-02-24 20:19 UTC, merged