Reduce compiler warnings
phac-nml/irida pull request #1183
Opened 2022-02-01 22:16 UTC by ericenns

## Description of changes
Refactored code to remove compiler warnings.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2022-02-02 14:30 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaOauthSecurityConfig.java
>  		return new CustomOAuth2ExceptionTranslator();
Compiler was giving warning about `Raw Type`, so I changed to the specific type i.e. `WebResponseExceptionTranslator<OAuth2Exception>` that `new CustomOAuth2ExceptionTranslator()` returns.

2022-02-02 14:30 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/config/security/IridaWebSecurityConfig.java
> -	private static final Logger logger = LoggerFactory.getLogger(IridaWebSecurityConfig.class);
Was unused.

2022-02-02 14:31 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/config/web/IridaUIWebConfig.java
> -	private static final String SPRING_PROFILE_DEVELOPMENT = "dev";
Removed unused variable, the rest of changes in file are just the formatting changes applied.

2022-02-02 14:32 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/database/changesets/AutomatedSISTRUpdate.java
> +					@SuppressWarnings("resource")
Fixed typo, rest of changes in file are formatting changes applied by the project formatting config.

2022-02-02 14:33 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/UploadedAssembly.java
> +public class UploadedAssembly extends GenomeAssembly {
Removed redundant implementation as `GenomeAssembly` already implements `VersionedFileFields` so it was not required.

2022-02-02 14:34 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/model/user/Role.java
> +public enum Role implements GrantedAuthority {
enums are already `Comparable` so that was not required.

2022-02-02 14:35 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisOutputFile.java
> +		return bytes;
Save as above file.

2022-02-02 14:36 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/processing/impl/FastqcFileProcessor.java
> +			sequenceFile.setFastQCAnalysis(analysisFastQC);
Analysis was being built twice so I just used the result of the first build. The rest of the changes in the file are due to the formatter.

2022-02-02 14:37 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/repositories/analysis/submission/AnalysisSubmissionRepositoryImpl.java
> -	@SuppressWarnings("unchecked")
Removed uncessary suppress warnings. Rest of the changes in the file are due to the formatter.

2022-02-02 14:37 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/repositories/remote/impl/Fast5ObjectRemoteRepositoryImpl.java
> -	private RemoteAPITokenService tokenService;
Removed unused service.

2022-02-02 14:38 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/repositories/sample/MetadataEntryRepositoryImpl.java
> +			TypedQuery<MetadataTemplateField> nativeQuery = entityManager.createQuery(queryString,
Switched to `TypeQuery` from `Query` which is type safe and removed unsafe type conversion warning.

2022-02-02 14:39 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/config/BreadCrumbInterceptor.java
> -	private String tryGetMessage(String noun, Locale locale) {
Removed unused method.

2022-02-02 14:40 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/config/BreadCrumbInterceptor.java
> -	private static class BreadCrumb {
Removed `private` from sub class decalaration which makes it package level accessible (i.e. any files in the same folder as this file). This was to remove `unused` warnings. I could have supressed those directly on the methods but I thought this was ok.

2022-02-02 14:40 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/config/thymeleaf/webpacker/util/WebpackerManifestParser.java
> -		Map<String, WebpackEntry> entries = new HashMap<>();
Removed unused Map.

2022-02-02 14:41 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/activities/dto/Activity.java
> +	public Long getId() {
Added in getters for attributes that were otherwise triggering `unused` compiler warnings.

2022-02-02 14:41 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/cart/CartGalaxyController.java
> -    private SampleService sampleService;
Removed unused service.

2022-02-02 14:42 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/clients/ClientsController.java
> +						Collections.singleton(ConstraintViolationImpl.forParameterValidation("client.redirect.required",
Changed to `Collections.singleton` for instantiating a single object set which removed type warnings.

2022-02-02 14:42 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/clients/ClientsController.java
> +						Collections.singleton(ConstraintViolationImpl.forParameterValidation("client.redirect.required",
Same as above comment.

2022-02-02 14:43 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/DataTablesColumnDefinitions.java
> +	public String getData() {
Added in method for `data` variable that was reporting unused compiler warnings.

2022-02-02 14:44 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/components/datatables/DataTablesExportToFile.java
> +		workbook.close();
Added in close of workbook, which was reported as not being closed in compiler warning.

2022-02-02 14:44 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/linelist/LineListController.java
> -		this.updateSamplePermission = updateSamplePermission;
removed `UpdateSamplePermission` which was reported as being unsued.

2022-02-02 14:47 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSamplesController.java
> -		Map<String, List<String>> result = new HashMap<>();
Removed unused Map. Rest of changes were due to formatter.

2022-02-02 14:47 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
> -	private final UpdateSamplePermission updateSamplePermission;
Removed unused `UpdateSamplePermission`

2022-02-02 14:47 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
> +		workbook.close();
Added in closure of workbook.

2022-02-02 14:48 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
> -	private Map<String, String> getErrorsFromViolationException(ConstraintViolationException e) {
Removed unused method.

2022-02-02 14:48 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
> -	private boolean canModifySample(Sample sample) {
Removed unused method.

2022-02-02 14:48 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSampleMetadataAjaxController.java
> -	private static final Logger logger = LoggerFactory.getLogger(ProjectSampleMetadataAjaxController.class);
Removed unused logger.

2022-02-02 14:48 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/metadata/ProjectSamplesMetadataTemplateController.java
> +		workbook.close();
Added in closure of workbook.

2022-02-02 14:49 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/settings/ProjectReferenceFileController.java
> -	private final MessageSource messageSource;
Removed unused logger, ReferenceFileService, and MessageSource.

2022-02-02 14:50 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIMetadataFileImportService.java
> +		if (extension.equals("xlsx")) {
Added in closure of workbook when xlsx as HSSWorkbooks are auto closed.

2022-02-02 14:50 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIMetadataImportService.java
> -		this.projectControllerUtils = projectControllerUtils;
Removed unused ProjectControllerUtils

2022-02-02 14:51 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineStartService.java
> -		this.cartService = cartService;
Removed unused CartService.

2022-02-02 14:51 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UISequenceFileService.java
> -	private static final Logger logger = LoggerFactory.getLogger(UISequenceFileService.class);
Removed unused logger.

2022-02-02 14:51 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/service/impl/sample/SampleServiceImpl.java
> -		this.assemblyRepository = assemblyRepository;
Removed unused GenomeAssemblyRepostiory.

2022-02-02 14:52 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/service/impl/user/UserGroupServiceImpl.java
> -	private static final Specification<UserGroupJoin> filterUserGroupJoinByRole(final UserGroupRole role) {
Removed unused filter specification.

2022-02-02 14:52 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/service/remote/ProjectHashingService.java
> -		this.projectService = projectService;
Removed unused ProjectService.

2022-02-02 14:52 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectAnalysisController.java
> -	private static String ANALYSIS_RESOURCES = "resource";
Removed unused class attribute.

2022-02-02 14:53 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/web/spring/view/CSVView.java
> +		AnalysisOutputFile sfr = (AnalysisOutputFile) ((ResponseResource<?>) model
Fix unsafe type cast warning.

2022-02-02 14:53 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/web/spring/view/FastaView.java
> +		IridaSequenceFile sfr = (IridaSequenceFile) ((ResponseResource<?>) model
Fix unsafe type cast warning.

2022-02-02 14:53 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/web/spring/view/FastqView.java
> +		SequenceFile sfr = (SequenceFile) ((ResponseResource<?>) model.get(RESTGenericController.RESOURCE_NAME))
Fix unsafe type cast warning.

2022-02-02 14:53 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/web/spring/view/GenbankView.java
> +		SequenceFile sfr = (SequenceFile) ((ResponseResource<?>) model.get(RESTGenericController.RESOURCE_NAME))
Fix unsafe type cast warning.

2022-02-02 14:53 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/web/spring/view/NewickFileView.java
> +		AnalysisOutputFile sfr = (AnalysisOutputFile) ((ResponseResource<?>) model
Fix unsafe type cast warning.

2022-02-02 14:54 UTC, ericenns commented on src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/LineListControllerTest.java
> -	private UpdateSamplePermission updateSamplePermission;
Removed unused UpdateSamplePermission.

2022-02-02 14:54 UTC, ericenns commented on src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/analysis/AnalysisAjaxControllerTest.java
> -		analysisOutputFileDownloadManager = mock(AnalysisOutputFileDownloadManager.class);
Removed unused analysisOutputFileDownloadManager.

2022-02-02 14:54 UTC, ericenns commented on src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/projects/ProjectsControllerTest.java
> -	private UpdateSamplePermission updateSamplePermission;
Removed unused UpdateSamplePermission.

2022-02-02 14:55 UTC, ericenns commented on src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/web/services/UIPipelineStartServiceTest.java
> -	private UICartService cartService;
Removed unused UICartService.

2022-02-02 14:55 UTC, ericenns commented on src/test/java/ca/corefacility/bioinformatics/irida/service/ProjectHashingServiceTest.java
> -    private ProjectService projectService;
Removed unused projectService.

2022-02-02 14:55 UTC, ericenns commented on src/test/java/ca/corefacility/bioinformatics/irida/service/impl/unit/sample/SampleServiceImplTest.java
> -	private Validator validator;
Removed unused Validator.

2022-02-02 21:04 UTC, deepsidhu85 requested changes
Looks good and thanks for taking care of this. Just one change below

2022-02-03 14:29 UTC, ericenns commented
> Looks good and thanks for taking care of this. Just one change below

For some reason I cannot comment on your direct code comment, but `AnalysisOutputFileDownloadManager` was already removed from `AnalysisAjaxController.java` in this PR. Specifically in 10e5f9b7bf779844462d83053d15cdd1f1986d8b

2022-02-03 14:37 UTC, deepsidhu85 commented
> > Looks good and thanks for taking care of this. Just one change below
> 
> For some reason I cannot comment on your direct code comment, but `AnalysisOutputFileDownloadManager` was already removed from `AnalysisAjaxController.java` in this PR. Specifically in [10e5f9b](https://github.com/phac-nml/irida/commit/10e5f9b7bf779844462d83053d15cdd1f1986d8b)

Weird it was still showing up in intellij on that branch. I will take another look

2022-02-07 19:43 UTC, deepsidhu85 approved these changes

2022-02-07 19:44 UTC, merged