Create new project metadata restrictions
phac-nml/irida pull request #1219
Opened 2022-03-15 15:47 UTC by deepsidhu85

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

Updated Create New Project to include step to set metadata field restrictions for when samples are in the cart and selected to be added to the new project.

**If samples selected from cart:**

![create-project-samples-metadata-restrictions](https://user-images.githubusercontent.com/25466211/158683455-96d20d55-3056-4e74-8ba0-8636e3636cac.png)

**If no samples selected from cart:**

![create-project-no-samples-metadata-restrictions](https://user-images.githubusercontent.com/25466211/158683735-ac4602d4-8004-445a-9070-4ecd4b957ed4.png)

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

~* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
* [X] Tests added (or description of how to test) for any new features.
* [X] User documentation updated for UI or technical changes.

2022-03-16 10:33 UTC, joshsadam commented
I just played with this, and it looks fantastic!  Really good job!

2022-03-21 14:49 UTC, joshsadam requested changes
There is only a couple seriously minor things to look at.

2022-03-21 14:49 UTC, joshsadam commented on src/main/webapp/resources/js/pages/projects/share/TargetMetadataRestriction.jsx
> +export function TargetMetadataRestriction({
Since you are repurposing this component for another page, maybe we should move it into the components directory.

2022-03-21 19:00 UTC, deepsidhu85 commented on src/main/webapp/resources/js/pages/projects/create/CreateProjectMetadataRestrictions.jsx
> +      render: (label, field) => <span className="t-field-label">{label}</span>,
Removed the unused field variable in 2395cbee75f21d7c238738d40a02173752c6d81d. I feel like it was there before but can't remember. Either way not required

2022-03-21 19:00 UTC, deepsidhu85 commented on src/main/webapp/resources/js/pages/projects/create/CreateProjectSamples.jsx
> +  const { data: projectSamples = {}, isLoading } = useGetCartSamplesQuery();
Because I love long variable names :) Lol just so it's in line with the new DTO being sent from the server!

2022-03-22 19:59 UTC, merged