User account page refactor - base
phac-nml/irida pull request #1248
Opened 2022-04-20 14:04 UTC by ksierks

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2022-04-28 17:11 UTC, ericenns requested changes
Just a few changes to Exception handling for the new endpoints you have added.

2022-04-28 18:04 UTC, ksierks commented on .github/workflows/ci-test.yml
> +        env:
I didn't catch that during a merge. Please see 37491f93d3999dee654464a7eede7b1f9907bf0e.

2022-04-28 18:12 UTC, ksierks commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/utilities/RoleUtilities.java
> +		//user.getSystemRole().equals(Role.ROLE_ADMIN) ???
Please see d061eff0a8c7eb3fe88bcf0e908fccc5ea44cf6c.

2022-04-28 18:13 UTC, ksierks commented on src/main/java/ca/corefacility/bioinformatics/irida/model/enums/ProjectRole.java
> +		for (UserGroupProjectJoin userGroupProjectJoin : userGroupProjectJoins) {
Please see 77d93bc7e438609f88890f055f587e314e1ccb12.

2022-04-29 02:45 UTC, ksierks commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSubscriptionService.java
> +	public String updateProjectSubscription(Long id, boolean subscribe, Locale locale) throws Exception {
Please see a9d2ed1d2cfabece8d3cd1c8c07a64a2bec0d04b.

2022-04-29 02:45 UTC, ksierks commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSubscriptionService.java
> +		try {
Please see a9d2ed1d2cfabece8d3cd1c8c07a64a2bec0d04b.

2022-04-29 02:46 UTC, ksierks commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPasswordResetService.java
> +				throw new Exception(messageSource.getMessage("server.password.reset.error.message", null, locale));
Please see a9d2ed1d2cfabece8d3cd1c8c07a64a2bec0d04b.

2022-04-29 02:46 UTC, ksierks commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPasswordResetService.java
> +			throw new Exception(messageSource.getMessage("server.password.reset.error.message", null, locale));
Please see a9d2ed1d2cfabece8d3cd1c8c07a64a2bec0d04b.

2022-04-29 02:46 UTC, ksierks commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectSubscriptionsAjaxController.java
> +		} catch (Exception e) {
Please see a9d2ed1d2cfabece8d3cd1c8c07a64a2bec0d04b.

2022-04-29 02:46 UTC, ksierks commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/PasswordResetAjaxController.java
> +		} catch (Exception e) {
Please see a9d2ed1d2cfabece8d3cd1c8c07a64a2bec0d04b.

2022-04-29 14:00 UTC, ericenns commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIProjectSubscriptionService.java
> +		} catch (Exception e) {
Can you change this to catching `EntityNotFoundException` since that is what `CrudService#read` throws when it cannot read a entity with a given id.

2022-04-29 18:17 UTC, ericenns approved these changes
👍 Looks good to me, thanks

2022-04-29 18:17 UTC, merged