WIP: Sample details refactor/ update sample file seq objects
phac-nml/irida pull request #1308
Opened 2022-06-07 20:52 UTC by deepsidhu85

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

Updated UI for displaying sample files in the Files tab of the SampleDetailViewer. This update allows us to use this component wherever sequencing objects / genome assemblies need to be listed.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

~* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
* [ ] Tests added (or description of how to test) for any new features.
~* [ ] User documentation updated for UI or technical changes.~

2022-06-09 20:11 UTC, joshsadam requested changes
Quick review before I leave for the day.  This one should not take long to get in.

2022-06-09 20:28 UTC, deepsidhu85 commented on src/main/webapp/resources/js/components/sequence-files/GenomeAssemblyListItem.jsx
> +        border: "solid 1px #EEE",
Still need to update the colors.. just wanted you to take a look and see what you think. I will get this and the comment above about the colors updated

2022-06-09 20:28 UTC, deepsidhu85 commented on src/main/webapp/resources/js/components/samples/components/GenomeAssemblyList.jsx
> +    notification.success({
The message just shows that the download has started not that it has completed successfully

2022-06-09 21:16 UTC, deepsidhu85 commented on src/main/webapp/resources/js/components/sequence-files/SequenceObjectListItem.jsx
> +        border: "solid 1px #EEE",
Updated in ef966187d0dfd7cb4ca35752a639b85f30ec3ec1

2022-06-09 21:16 UTC, deepsidhu85 commented on src/main/webapp/resources/js/components/sequence-files/SequenceObjectListItem.jsx
> +        <div style={{ marginTop: sequenceObject.qcEntries?.length ? -50 : 0 }}>
Added in ef966187d0dfd7cb4ca35752a639b85f30ec3ec1

2022-06-09 21:17 UTC, deepsidhu85 commented on src/main/webapp/resources/js/components/sequence-files/SequenceObjectListItem.jsx
> +          key={
Redone in ef966187d0dfd7cb4ca35752a639b85f30ec3ec1

2022-06-09 21:17 UTC, deepsidhu85 commented on src/main/webapp/resources/js/components/samples/components/GenomeAssemblyList.jsx
> +    actions.push(
Added to array declaration in ef966187d0dfd7cb4ca35752a639b85f30ec3ec1

2022-06-09 21:17 UTC, deepsidhu85 commented on src/main/webapp/resources/js/components/sequence-files/GenomeAssemblyListItem.jsx
> +        border: "solid 1px #EEE",
Updated in ef966187d0dfd7cb4ca35752a639b85f30ec3ec1

2022-06-10 10:13 UTC, joshsadam commented on src/main/webapp/resources/js/components/sequence-files/GenomeAssemblyListItem.jsx
> +        border: "solid 1px #EEE",
See comment above

2022-06-10 10:28 UTC, joshsadam commented
This looks so much better, thank you. 2 suggestions:
1. Add a little padding on both sides of the avatars, it looks crowded.
2. I know why you put file size at the end, I like the way it looks, it does break the fact that the action buttons should always be at the end. What if you were to make the action buttons a fixed width, and then put the qc and files size before them?

2022-06-10 10:30 UTC, joshsadam commented
Sorry, one other thing I just noticed.  After uploading a file, I know you are querying the server for the qc status, but once it is good it seems to keep hitting  the server:
![image](https://user-images.githubusercontent.com/11295750/173046872-601c8076-d2f1-4167-973e-bfb7954c4ace.png)

2022-06-10 11:47 UTC, deepsidhu85 commented
> Thanks. I don't know if `grey4` would be too dark, but there is a default `BORDER_LIGHT` constant in borders.js.

Nope it still looks great. Updated in d9ac9542450c9f3fb277d4bfee8e658a96d2cbde

2022-06-10 11:48 UTC, deepsidhu85 commented
> Sorry, one other thing I just noticed. After uploading a file, I know you are querying the server for the qc status, but once it is good it seems to keep hitting the server: ![image](https://user-images.githubusercontent.com/11295750/173046872-601c8076-d2f1-4167-973e-bfb7954c4ace.png)

I have not been able to recreate this even after trying with different number of files per upload. If there's anything specific that you did let me know and I can try out the same steps

2022-06-10 11:50 UTC, deepsidhu85 commented
> This looks so much better, thank you. 2 suggestions:
> 
> 1. Add a little padding on both sides of the avatars, it looks crowded.
> 2. I know why you put file size at the end, I like the way it looks, it does break the fact that the action buttons should always be at the end. What if you were to make the action buttons a fixed width, and then put the qc and files size before them?

Added a marginLeft to the avatars (d9ac9542450c9f3fb277d4bfee8e658a96d2cbde) which doesn't make it look as crowded. I tried putting a padding on but it shifts the icon inside the avatar

2022-06-10 16:16 UTC, deepsidhu85 commented
> This looks so much better, thank you. 2 suggestions:
> 
> 1. Add a little padding on both sides of the avatars, it looks crowded.
> 2. I know why you put file size at the end, I like the way it looks, it does break the fact that the action buttons should always be at the end. What if you were to make the action buttons a fixed width, and then put the qc and files size before them?

Moved action buttons to the end in 66af80a9f4bd217959db51fd3b6dcc4232640fc2.

2022-06-14 16:27 UTC, joshsadam requested changes
Just that one last change

2022-06-14 18:53 UTC, merged