Object store/ azure testing
phac-nml/irida pull request #1384
Opened 2022-10-21 03:09 UTC by deepsidhu85

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2022-10-31 13:58 UTC, ericenns requested changes
In general this is looking good, just a few comments below. Also could you update `run-tests.sh` to start the docker container for the corresponding tests that require it.

2022-10-31 15:28 UTC, deepsidhu85 commented on .github/workflows/ci-test.yml
> +      azurite:
The service entry doesn't allow an `if` statement. Instead I added the docker stuff for Azurite in the `steps` section. It now only starts up when running the FileSystem tests.

2022-10-31 15:31 UTC, deepsidhu85 commented on src/test/java/ca/corefacility/bioinformatics/irida/ria/unit/cloud/IridaFileStorageAzureUtilityTest.java
> +public class IridaFileStorageAzureUtilityTest implements IridaFileStorageTestUtility {
Converted it over to an IntegrationTest. I decided to create a new tag for the FileSystem as this allows us to just start up the azurite docker container for these specific tests. If we reused the `Service` tag then we would have azurite starting up for those tests as well.

2022-11-02 12:38 UTC, ericenns approved these changes
👍 I have tested this locally and it works for me, thanks!

2022-11-02 12:38 UTC, merged