User name set as 'Group Name' fixed
phac-nml/irida pull request #1450
Opened 2023-01-20 16:06 UTC by joshsadam

## Description of changes

Updated column name for `User` in the Admin User Groups table

## Related issue

N/A

## Checklist

Things for the developer to confirm they've done before the PR should be accepted:

*   [x] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
*   [ ] ~Tests added (or description of how to test) for any new features.~
*   [ ] ~User documentation updated for UI or technical changes.~

2023-01-20 21:28 UTC, ericenns requested changes
Changelog comment is in the wrong place, otherwise good.

2023-01-20 21:28 UTC, ericenns commented on CHANGELOG.md
> +* [UI]: Fixed bug where the `User` column was named `User Group` on the admin User Groups page. [See PR 1450](https://github.com/phac-nml/irida/pull/1450)
This should be in the section above

2023-01-20 21:31 UTC, joshsadam commented on CHANGELOG.md
> +* [UI]: Fixed bug where the `User` column was named `User Group` on the admin User Groups page. [See PR 1450](https://github.com/phac-nml/irida/pull/1450)
You are correct, Fixed

2023-01-23 16:30 UTC, ericenns approved these changes
👍

2023-01-24 13:53 UTC, merged