Metadata uploader to use React Router Outlet
phac-nml/irida pull request #1464
Opened 2023-02-07 02:20 UTC by ksierks

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2023-02-07 17:44 UTC, joshsadam requested changes
You nailed it with this :)  There are two nit picky things I would like you to clean up, but besides that, great job.

2023-02-07 19:02 UTC, ksierks commented on src/main/webapp/resources/js/pages/projects/samples-metadata-import/redux/importReducer.ts
> +export type Status = "wait" | "process" | "finish" | "error";
Of course. Please see c6884b5376af2f9d86cbb92b04350cc87e48b691.

2023-02-07 19:02 UTC, ksierks commented on src/main/webapp/resources/js/pages/projects/samples-metadata-import/index.tsx
> +            element={<SampleMetadataImportWizard current={0} />}
I missed it. Please see fea6b558366e04c831ec3fbcb3fa6f1b23f2627b.

2023-02-08 20:16 UTC, joshsadam approved these changes

2023-02-08 20:16 UTC, merged