Fix for metadata uploader overwriting existing data
phac-nml/irida pull request #1489
Opened 2023-04-26 18:55 UTC by ksierks

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Fixes #1488.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2023-05-01 16:08 UTC, joshsadam requested changes
This definitely works as advertised.  My only request is that you add a test to confirm the number of metadata fields on a sample pre and post file upload.

2023-05-01 21:11 UTC, ksierks commented
> This definitely works as advertised.  My only request is that you add a test to confirm the number of metadata fields on a sample pre and post file upload.

Please see latest commit for better test.

2023-05-02 10:22 UTC, joshsadam reviewed
This looks great.  Double-check the failing test.

2023-05-02 10:22 UTC, joshsadam commented on src/test/java/ca/corefacility/bioinformatics/irida/ria/integration/projects/ProjectSampleMetadataImportPageIT.java
> +		assertEquals("AB", sampleDetailsViewer.getValueForMetadataField("Province"), "Should have uploaded metadata");
This looks great, thanks.

2023-05-02 19:31 UTC, joshsadam approved these changes
Thanks for updating the test.

2023-05-09 13:58 UTC, ericenns approved these changes
Looks good to me!

2023-05-09 13:59 UTC, merged