WIP: Object store/ gui
phac-nml/irida pull request #761
Opened 2020-07-20 23:36 UTC by deepsidhu85

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

Updated GUI components to work with Amazon AWS S3 and Microsoft Azure object store.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

~* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.~
~* [ ] Tests added (or description of how to test) for any new features.~
~* [ ] User documentation updated for UI or technical changes.~

2020-11-26 19:57 UTC, tom114 requested changes
Haven't tested its function yet but a couple quick comments and some unused variables.  I'll actually test it soon.

2020-11-26 20:53 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageUtility.java
> +	public byte[] readAllBytes(Path file);
Yup all that is used for is the FastQC images and any analysis outputs which are images. Looks like it is used in FileUtilities.java as well in the createAnalysisOutputFileZippedResponse method which was changed from `byte[] bytes = objectMapper.writeValueAsBytes(file);` to `byte[] bytes = file.getBytesForFile();` to work with out object store stuff. Anywhere the files are larger they are streamed using the getFileInputStream method.

2020-11-27 16:42 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/files/SequenceFileController.java
>  		Path path = sequenceFile.getFile();
Removed in 812a1b86c4c0abf1994668d24b8080b497cf3d34

2020-11-30 20:33 UTC, tom114 requested changes

2020-11-30 20:33 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisAjaxController.java
> +				logger.error("Unable to read input stream for file");
Add the throwable cause here in the error logging so we can see the stack trace please.

2020-11-30 20:33 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/files/SequenceFileController.java
> +			logger.error("Unable to read input stream from file", e);
Same here.  Add the cause.

2020-11-30 21:24 UTC, tom114 approved these changes

2020-11-30 21:24 UTC, merged