WIP: Object store/ rest api
phac-nml/irida pull request #768
Opened 2020-07-31 18:41 UTC by deepsidhu85

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2021-09-03 17:35 UTC, tom114 requested changes
Thanks for the work here @deepsidhu85 .  A few questions and modifications below.

2021-09-08 15:45 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/GenomeAssembly.java
> +	}
When using the rest api to list a sample and its files it shows you where the file is located. Currently only displays the location depending on the value set in the irida conf file for the storage type

2021-09-08 15:45 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/SequenceFile.java
> +	}
Same as above

2021-09-13 14:57 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/SequenceFile.java
> +	public Long getFileSizeBytes() {
This method is still used when displaying the size of files in a sample and sequencing run. I will end up updating this during my sample details refactor so just going to leave it for now

2021-09-13 16:51 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/repositories/filesystem/IridaFileStorageAwsUtilityImpl.java
> +		this.storageType = StorageType.AWS;
Updated in a256989b5b322f9e57d2818a7127f21d99ea05d3

2021-09-13 16:51 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/web/spring/view/CSVView.java
> +			OutputStream os = response.getOutputStream();
Updated in a256989b5b322f9e57d2818a7127f21d99ea05d3

2021-09-13 16:52 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/RESTAnalysisSubmissionController.java
> +			ByteArrayResource fileContents = new ByteArrayResource(inputStream.readAllBytes());
This method is being re-added into the rest api in a separate PR. I will update it to not read the entire output file into memory once that PR is merged up

2021-11-02 15:31 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/model/assembly/GenomeAssembly.java
> +	}
Ok thanks.  This is likely a good addition.

2021-11-02 15:35 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/SequenceFile.java
> +	public Long getFileSizeBytes() {
Thanks I see this is being ignored now.  It's an expensive call if we have it being run in the REST API when it isn't being used.  If you're going to remove one of the old methods, can you throw a `@Deprecated` on the one you're planning to remove?  That way we can mark which one is going to go away.

2021-11-02 15:59 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/SequenceFile.java
> +	public Long getFileSizeBytes() {
Sure! Will add that

2021-11-02 17:45 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/model/sequenceFile/SequenceFile.java
> +	public Long getFileSizeBytes() {
My mistake. Looking into it further both the getFileSizeBytes and getFileSize methods are used. There are certain places where we require a human readable file size in the UI and certain places where we only require the size in bytes

2022-02-21 18:10 UTC, deepsidhu85 commented
@ericenns Here is a screenshot of the rest api call that shows the representation of the file and its storage location:

![restapicall](https://user-images.githubusercontent.com/25466211/155007651-343c9f6d-18f8-4e27-bb7d-275e2335548a.jpg)

2022-07-25 21:11 UTC, ericenns approved these changes
I think this looks good enough to merge. Not sure exactly how I feel about returning file path in the rest api for non local storage files, but I understand why you left it. It could still be addressed in the larger PR.

2022-07-25 21:11 UTC, merged