Add password authentication for SMTP server
phac-nml/irida pull request #795
Opened 2020-09-08 22:04 UTC by innovate-invent

## Description of changes
Add password parameter for smtp user authenitcation

## Related issue
#757 

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2020-09-08 22:37 UTC, innovate-invent commented
I am not sure how tests for this should be done as it would require an smtp server.
I may also need to expose more smtp parameters to configure the different TLS settings.

2020-12-03 21:49 UTC, tom114 requested changes
Thanks for the PR @innovate-invent.  Since this is adding more customization options for connecting to a mail server, I asked below for a small refactor for how the default config values are set & read.  Since some may be optional settings now, it would be a good idea to add some `null` & empty checks for them before setting them on the mail sender.

Feel free to give me a shout if you have any questions about the requested changes.

2020-12-03 22:12 UTC, innovate-invent commented on src/main/resources/configuration.properties
> +mail.server.port=25
done

2020-12-03 22:14 UTC, innovate-invent commented on src/main/java/ca/corefacility/bioinformatics/irida/config/services/WebEmailConfig.java
> +		if (!(UNCONFIGURED_PASSWORD_VALUE.equals(password) || password.isBlank())) {
port doesn't require a check as Java sets its default value

2021-01-19 14:07 UTC, tom114 requested changes
Thanks @innovate-invent , this change should be good to go!  Can you clear up the conflict in the changelog and it should be ready to merge.

2021-01-19 18:38 UTC, tom114 approved these changes

2021-01-19 18:39 UTC, merged