Fix remote oauth remote connection details
phac-nml/irida pull request #797
Opened 2020-09-09 12:37 UTC by joshsadam

## Description of changes
Re-wrote remote connection details to use full React component and use same button to connect to oath as the listing table.

## Related issue

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2020-09-14 16:17 UTC, deepsidhu85 requested changes

2020-09-14 16:17 UTC, deepsidhu85 commented on CHANGELOG.md
> +* [UI]: Upprojdated Remote API Connection details page to use full Ant Design and updated oauth.
Typo

2020-09-14 17:28 UTC, joshsadam commented on CHANGELOG.md
> +* [UI]: Upprojdated Remote API Connection details page to use full Ant Design and updated oauth.
Fixed in 9d47828

2020-09-15 15:06 UTC, deepsidhu85 approved these changes

2020-09-15 15:06 UTC, merged