Fix remoate oath create remote project
phac-nml/irida pull request #801
Opened 2020-09-11 18:06 UTC by joshsadam

## Description of changes
What did you change in this pull request?  Provide a description of files changed, user interactions changed, etc.  Include how to test your changes.

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2020-09-15 17:04 UTC, deepsidhu85 requested changes

2020-09-15 17:23 UTC, joshsadam commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/projects/ProjectsController.java
> +		private final RemoteStatus remoteStatus;
That internal class is not used. Removed in cf21801406f8704b290fe2765b38dd26ac6bd17f

2020-09-15 17:25 UTC, joshsadam commented on src/main/webapp/resources/js/apis/remote-api/remote-api.js
> +
Updated in 76197dc

2020-09-15 17:32 UTC, joshsadam commented on src/main/webapp/resources/js/components/remote-api/CreateRemoteProjectSyncForm.jsx
> +                    REMOTE PROJECT URL
Updated in 822fbe4

2020-09-15 17:32 UTC, joshsadam commented on src/main/webapp/resources/js/components/remote-api/CreateRemoteProjectSyncForm.jsx
> +                      Set url manually
Updated in 822fbe4

2020-09-15 17:34 UTC, joshsadam commented on src/main/webapp/resources/js/pages/admin/components/remote-connections/RemoteApiStatus.jsx
> +  function updateConnectionStatus() {
Updated in 611706c

2020-09-16 13:44 UTC, deepsidhu85 approved these changes

2020-09-16 16:43 UTC, merged