Pipeline Launch: File Selection
phac-nml/irida pull request #889
Opened 2020-12-14 17:13 UTC by joshsadam

## Description of changes
Display a list of sample and their files **that can be run** on the currently selected pipeline.

![image](https://user-images.githubusercontent.com/11295750/102112467-5bbc0100-3dfd-11eb-8c65-120b85212206.png)

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2020-12-17 22:03 UTC, deepsidhu85 reviewed
First thought looking at the image you attached. The email on pipeline completion checkbox is missing. Also, I don't know how I feel about the section headings with the line

2020-12-18 13:13 UTC, joshsadam commented
What does the "email on pipeline completion" have to do with displaying files?  I can re-work the headings.

2020-12-18 19:04 UTC, deepsidhu85 requested changes
Overall looks good. Just a few things to change

2020-12-18 19:58 UTC, joshsadam commented on src/main/webapp/resources/js/apis/pipelines/pipelines.js
> +import { notification } from "antd";
Removed in c22841d88426c7aff7446e90af83e91ad7044b53

2020-12-18 20:02 UTC, joshsadam commented on src/main/java/ca/corefacility/bioinformatics/irida/ria/web/services/UIPipelineSampleService.java
> +				LaunchSample ls = new LaunchSample(sample, project);
Updated in 816dd5f6219aa976df98061c945d3d578c9dbac5

2020-12-18 20:05 UTC, joshsadam commented on src/main/webapp/resources/js/pages/launch/LaunchFiles.jsx
> +          data.filter((s) => s.files.length).map((s) => s.files[0].identifier)
Updated in 6da8d9bff13a33be6bceec4b4f0a2a30a50ed075

2020-12-18 20:08 UTC, joshsadam commented on src/main/webapp/resources/js/pages/launch/LaunchFiles.jsx
> +        setVisibleSamples(samples.filter((s) => s.files.length));
Updated in ab4014ebb2261779550f82d5caffb6c5e7d95abf

2020-12-18 20:09 UTC, joshsadam commented on src/main/webapp/resources/js/pages/launch/LaunchFiles.jsx
> +
Um... nope

2020-12-18 20:12 UTC, joshsadam commented on src/main/webapp/resources/js/pages/launch/LaunchFiles.jsx
> +      setSamples(samples.filter((s) => sample.id !== s.id));
I really like the letter `s`, this is the 3rd time you have asked me to change it, I am getting a little frustrated.

2020-12-18 20:12 UTC, joshsadam commented on src/main/webapp/resources/js/pages/launch/LaunchFiles.jsx
> +      setSamples(samples.filter((s) => sample.id !== s.id));
I really like the letter `s`, this is the 3rd time you have asked me to change it, I am getting a little frustrated.

2020-12-18 20:13 UTC, joshsadam commented on src/main/webapp/resources/js/pages/launch/LaunchFiles.jsx
> +      setSamples(samples.filter((s) => sample.id !== s.id));
Updated in 1f439228120aafd4fb6c7818526a305e0498fc0e

2020-12-18 20:26 UTC, joshsadam commented on src/main/webapp/resources/js/pages/launch/LaunchFiles.jsx
> +
Ok, updated in 36217e186faf24e3afa542f73527c487c7048c32

2020-12-21 21:01 UTC, deepsidhu85 approved these changes

2020-12-21 21:02 UTC, merged