WIP: Announcements upgrade - Part #2
phac-nml/irida pull request #937
Opened 2021-02-10 13:47 UTC by ksierks

## Description of changes

Fixes the following issues:

#913 - Automatically display high priority announcements UI enhancement
#918 - Handle announcements for new users UI enhancement
#930 - Move announcements to the main navigation panel UI enhancement

## Related issue
Link to the GitHub issue this pull request addresses using the `#issuenum` format.  If it completes an issue, use `Fixes #issuenum` to automatically close the issue.

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2021-03-11 19:42 UTC, joshsadam approved these changes
Yay!!

2021-03-13 00:43 UTC, tom114 requested changes
We should reshoot a few more screenshots on the dashboard docs with the new features please. Otherwise this is looking really good!

2021-03-15 14:51 UTC, ksierks commented on doc/user/user/dashboard/index.md
> +The IRIDA platform uses announcements to inform users of important information. Some examples may include:
Please see 5e2838654c292169744b76ac227932faf1e14245 and 2fed7439ce1ba61f340cb64c8c8843112941116a.

2021-03-16 14:05 UTC, tom114 approved these changes

2021-03-16 15:10 UTC, merged