HOTFIX: Added ownership flag to copying sample to project in REST API
phac-nml/irida pull request #950
Opened 2021-02-23 17:42 UTC by tom114

## Description of changes
Added an ownership flag API endpoint copying samples to another project via the REST API.  Add ownership flag as URL variable with `?ownership=true/false`.  Default is `false`

## Related issue
N/A

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

* [ ] CHANGELOG.md (and UPGRADING.md if necessary) updated with information for new change.
* [ ] Tests added (or description of how to test) for any new features.
* [ ] User documentation updated for UI or technical changes.

2021-02-23 23:05 UTC, deepsidhu85 requested changes

2021-02-23 23:05 UTC, deepsidhu85 commented on src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java
> +	 * @param ownership Whether the recieving project should have ownership of the sample
Typo: `recieving`

2021-02-24 16:14 UTC, tom114 commented on src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/projects/RESTProjectSamplesController.java
> +	 * @param ownership Whether the recieving project should have ownership of the sample
Fixed in 9f4f81a

2021-02-24 16:58 UTC, deepsidhu85 approved these changes

2021-02-24 16:59 UTC, merged