Project Settings > details
phac-nml/irida pull request #964
Opened 2021-03-22 18:19 UTC by joshsadam

## Description of changes
Refactoring the project settings pages.  This is is to handle **only** project details.  Updates the way the data is fetch and updated to us redux.

## Related issue
N/A

## Checklist
Things for the developer to confirm they've done before the PR should be accepted:

N/A

2021-04-13 16:03 UTC, deepsidhu85 requested changes
Overall looks great and works as expected. Just a few changes for now

2021-04-13 16:03 UTC, deepsidhu85 commented on src/main/webapp/resources/js/apis/projects/settings.js
> +export const putProcessingCoverage = async (projectId, coverage) => {
There's a few other places where you use `putXX`. It just feels dirty to me. So if you could update those as well that'd be great

2021-04-15 18:51 UTC, joshsadam commented on src/main/webapp/resources/js/apis/projects/settings.js
> +export const putProcessingCoverage = async (projectId, coverage) => {
Updated in 2d2bfd6eed0ee17428b9087e52e0e4e00d1dd8d2

2021-04-15 19:45 UTC, joshsadam commented on src/main/webapp/resources/js/pages/projects/settings/components/processing/AnalysisTemplates.jsx
> +  const removeAutomatedPipeline = (template) =>
Updated in 5352a80

2021-04-15 19:46 UTC, joshsadam commented on src/main/webapp/resources/js/pages/projects/redux/pipelinesSlice.js
> +  async ({ templateId, projectId }) => {
Updated in 5352a80

2021-04-15 19:49 UTC, joshsadam commented on src/main/webapp/resources/js/pages/projects/settings/components/processing/ProcessingPriorities.jsx
> +    { value: "LOW", label: i18n("AnalysisDetailsPriority.LOW") },
Don;t want to change more now.  Maybe a future idea

2021-04-15 19:51 UTC, deepsidhu85 commented on src/main/webapp/resources/js/pages/projects/settings/components/processing/ProcessingPriorities.jsx
> +    { value: "LOW", label: i18n("AnalysisDetailsPriority.LOW") },
I will give you a pass on this one :)

2021-04-16 19:42 UTC, deepsidhu85 approved these changes

2021-04-16 19:42 UTC, merged